### ISSUE TITLE
Configure Gatsby to perform slash-less redirects

### ISSUE THREAD

**Issue by sabbyanandan** [spring-io/dataflow.spring.io#108]
As a developer, I'd like to configure Gatsby to do the slash-less redirect to an HTTPs version. In general, though, we should probably avoid using the slash-less URLs in the first place.

Specifically, look at `Functional Composition` link in the [FAQ](https://dataflow-preview.cfapps.io/docs/feature-guides/streams/function-composition?origin_team=T024LQKAS).

**Comment by oodamien** [comment]
Fixed on https://github.com/spring-io/dataflow.spring.io/commit/b6fc8357066e32fd3c15702b00acea5c94b45c6a
