### ISSUE TITLE
not clear: stream-developer-guides/4-continuous-delivery/  suggest rabbitMQ 

### ISSUE THREAD

**Issue by laniakea001** [spring-io/dataflow.spring.io#112]
github location:dataflow.spring.io/content/documentation/pages/3-stream-developer-guides/4-continuous-delivery/1-cd-basics.md 
http location:
https://dataflow.spring.io/docs/stream-developer-guides/continuous-delivery/cd-basics/

when we learn how to "Continuous Delivery of streaming applications",previous we use rabbit,why 
![图片](https://user-images.githubusercontent.com/32099721/62355143-030a0200-b541-11e9-8d49-78110190c4d8.png)

**Comment by sabbyanandan** [comment]
Thanks, @laniakea001. Good catch! We will fix it via: https://github.com/spring-io/dataflow.spring.io/pull/113.

Please feel free to submit a PR next time. 😄
