### ISSUE TITLE
"Delegate listener must not be null" following getting start guide

### ISSUE THREAD

**Issue by RaccoonDev** [spring-io/dataflow.spring.io#116]
Following getting started guide on Java 12 I faced the issue running "timestamp" batch job. The examples provide 1.3.0.RELEASE version for the "timestamp" batch task, however, the "java.lang.IllegalArgumentException: Delegate listener must not be null" is thrown when the task is being executed.

Switching to 2.1.0.RELEASE task version fixes the issue.

I would change documentation to provide version 2.1.0.RELEASE for the task to avoid confusion for people who are just starting. I've created PR for the change.

**Comment by sabbyanandan** [comment]
Thank you for the PR, @RaccoonDev!

**Comment by RaccoonDev** [comment]
You're welcome! Hope that will help.

**Comment by sabbyanandan** [comment]
Addressed in https://github.com/spring-io/dataflow.spring.io/commit/64ed2ff51fa866cdba08427a2e46c99330204287.
