### ISSUE TITLE
Test and document SCDF + Prometheus for Streams/Tasks on Cloud Foundry

### ISSUE THREAD

**Issue by sabbyanandan** [spring-io/dataflow.spring.io#129]
In continuation with what we have done for Prometheus + RSocket on K8s, we would want to document the prereqs and the configuration setup to integrate with Prometheus + RSocket setup on Cloud Foundry.

**Acceptance:**
- Include prereqs
- Include configuration steps 
- Use the same stream and task demo, but run it on CF instead against Prometheus

**Comment by sabbyanandan** [comment]
Based on the experiments running Prom + Graf as binary blobs in PAS, the goal here is to simply just highlight what is required to configure the monitoring system with SCDF. We shall assume that Prom + Graf is running elsewhere and that they are accessible via routable hosts/URIs.

**Comment by tzolov** [comment]
resolved after 74ba92e4cba96d18f4bcb6b94cb5170cb8b6a940
