### ISSUE TITLE
docker-compose-postrges.yaml link is broken

### ISSUE THREAD

**Issue by cppwfs** [spring-io/dataflow.spring.io#139]
In the `Using PostgreSQL Instead of MySQL` section we have  link for users to obtain the docker compose postgres yaml file as shown here:
wget https://raw.githubusercontent.com/spring-cloud/spring-cloud-dataflow/v2.2.1.RELEASE/spring-cloud-dataflow-server/docker-compose-postgres.yml

However this link is not available to 2.3.0.

**Comment by sabbyanandan** [comment]
Relates to https://github.com/spring-io/dataflow.spring.io/pull/136.

**Comment by tzolov** [comment]
In fact all docker compose files are broken
```

wget https://raw.githubusercontent.com/spring-cloud/spring-cloud-dataflow/v2.2.1.RELEASE/spring-cloud-dataflow-server/docker-compose-prometheus.yml

wget https://raw.githubusercontent.com/spring-cloud/spring-cloud-dataflow/v2.2.1.RELEASE/spring-cloud-dataflow-server/docker-compose-influxdb.yml

wget https://raw.githubusercontent.com/spring-cloud/spring-cloud-dataflow/v2.2.1.RELEASE/spring-cloud-dataflow-server/docker-compose-postgres.yml

wget https://raw.githubusercontent.com/spring-cloud/spring-cloud-dataflow/v2.2.1.RELEASE/spring-cloud-dataflow-server/docker-compose-rabbitmq.yml
```
Including the main docker-compose.yml, which is pointing to old file that doesn't correspond to the documentation in the page.
```
wget https://raw.githubusercontent.com/spring-cloud/spring-cloud-dataflow/v2.2.1.RELEASE/spring-cloud-dataflow-server/docker-compose.yml
```
