### ISSUE TITLE
Microsite has issues with direct access to webpages

### ISSUE THREAD

**Issue by Kevintjeb** [spring-io/dataflow.spring.io#143]
Hi, 

When navigating to the local machine instruction from the home page, the page is available.
https://dataflow.spring.io/ 
-> 'getting started button' (https://dataflow.spring.io/getting-started/) 
-> 'local machine button' (https://dataflow.spring.io/docs/installation/local/)

Yet when you refresh, or go to the url directly, the page is 403 forbidden.
https://dataflow.spring.io/docs/installation/local/ -> 403 forbidden

I assume it has something to do with the fact that the content is loaded dynamically when going from the homepage, and not requested as a single html page.

**Comment by oodamien** [comment]
Hi @Kevintjeb,
Thanks for this report, we are investigating on this issue.

**Comment by oodamien** [comment]
Fixed -
