### ISSUE TITLE
Helm Configuration Does not include Grafana or Prometheus

### ISSUE THREAD

**Issue by derrick-solstice** [spring-io/dataflow.spring.io#148]
The Helm deployment does not include Grafana or Prometheus and requires a significant amount of manual setup that is not necessary in the Docker Compose  start up. 

Can we update the Helm Stable Chart to include these?  If so, would that come from here or should I open an Issue on the Helm Repo?

**Comment by sabbyanandan** [comment]
Hi, @derrick-solstice. We track the helm-chart issues in [SCDF backlog](https://github.com/spring-cloud/spring-cloud-dataflow/issues). 

As an FYI, when 2.3 GA is released, we will update the SCDF chart to consume the upstream dependencies. We can consider adding the Prometheus stack as part of the stack upgrade.

So yeah, feel free to move the issue to SCDF.

**Comment by sabbyanandan** [comment]
One other thing. In v2.3, the Prometheus + Grafana integration is entirely revamped. Feel free to try out the latest updates to the infrastructure from [v2.3 BUILD-SNAPSHOT docs](https://dataflow.spring.io/docs/2.3.0.SNAPSHOT/installation/kubernetes/kubectl/#deploy-prometheus-and-grafana).

**Comment by derrick-solstice** [comment]
I created a new issue in the SCDF Backlog,  IN the interim i will attempt to continue my deployment to GKE through the `kubectl` dependencies and i'll take a look at the docs!  Thank you so much.
