### ISSUE TITLE
Update the CI plan to include "linkinator" as a task

### ISSUE THREAD

**Issue by sabbyanandan** [spring-io/dataflow.spring.io#159]
We have had reports of broken links. 

https://github.com/spring-io/dataflow.spring.io/pull/158 appears to fix the Initializr breaking changes, but there could be others lurking in the site.

Chores:

- [x] Fix the broken links
- [x] Run linkinator against each of the supported versions
- [x] Configure/fix the CI plan

**Comment by oodamien** [comment]
Configure `linkinator` on the CI.

**Comment by oodamien** [comment]
Wait for: https://github.com/JustinBeckwith/linkinator/issues/37
Or create a remark plugin to fix internal links.
