### ISSUE TITLE
Make new release features, blogs, and promotion material visible in the Microsite

### ISSUE THREAD

**Issue by sabbyanandan** [spring-io/dataflow.spring.io#169]
As a user, I'm unable to find where to navigate to find the FAQ.  I have to click the "Documentation -> Resources" before you see it in the left pane; maybe it would be helpful to add FAQs in this box. If not, at least we can update the description in the `Resources` tile with FAQ in it, so it is visible.

![image](https://user-images.githubusercontent.com/1562654/70472651-4f7fc400-1a84-11ea-9c52-3f1dac785be7.png)

Let's take this opportunity to revisit how do we want to surface the latest GA release and feature-blogs under "Resources", as well.

I started an internal discussion [here](https://pivotal.slack.com/archives/CDSHV1GV9/p1575925065007100).

cc:/ @garyrussell

**Comment by oodamien** [comment]
Should we create a dedicate tile for the FAQ?

**Comment by sabbyanandan** [comment]
Hmm, FAQ, a new tile .. maybe. We need to also think about where to host the latest release blogs. A new tile everything might be chatty. I'd be happy to discuss other options, as well.

@markpollack: What are your thoughts?

**Comment by oodamien** [comment]
![faq](https://user-images.githubusercontent.com/487067/70811914-da372a80-1dc6-11ea-8c8c-7ebc6bcdbdc6.png)
