### ISSUE TITLE
Clarify how to whitelist properties and the use of metadata artifact for custom apps

### ISSUE THREAD

**Issue by sabbyanandan** [spring-io/dataflow.spring.io#181]
We discuss [whitelisting properties](https://docs.spring.io/spring-cloud-dataflow/docs/2.3.0.RELEASE/reference/htmlsingle/#spring-cloud-dataflow-stream-app-whitelisting) separately, but without the [dedicated metadata artifact](https://docs.spring.io/spring-cloud-dataflow/docs/2.3.0.RELEASE/reference/htmlsingle/#spring-cloud-dataflow-stream-app-metadata-artifact), the whitelisted properties won't show up in the UI or Shell.

This is not clearly defined in the ref. guide, and it is not described in the Microsite either. The stream and batch developer guide can include an explicit section about how this will be used with SCDF.

**Comment by tzolov** [comment]
I did a quick test using the [Spring Initializr](https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/2.1.2.RELEASE/single/spring-cloud-stream.html#_quick_start) to create a new Sink app.

I used the `Spring Cloud`, `Spring for Apache Kafka` and `Spring Web` (later is required for the SCDF to be able to check the status of the app) as dependencies. 

Then i created to property classes: 
```java
@ConfigurationProperties("my")
public class MyLogConsumerProperties {

	public String getDugong() {
		return dugong;
	}

	public void setDugong(String dugong) {
		this.dugong = dugong;
	}

	private String dugong;
}
```
and 
```java
@ConfigurationProperties("other")
public class MyOtherProperties {

	public String getOrca() {
		return orca;
	}

	public void setOrca(String orca) {
		this.orca = orca;
	}

	private String orca;
}
```
And registered them with the Sink application:
```java
@SpringBootApplication
@EnableBinding(Sink.class)
@EnableConfigurationProperties({ MyLogConsumerProperties.class, MyOtherProperties.class })
public class MyLogConsumerApplication {
...
}
```

Then i created a `META-INF/spring-configuration-metadata-whitelist.properties` file with this content:
```
configuration-properties.classes=com.example.mylogconsumer.MyLogConsumerProperties
configuration-properties.names=other.orca
```
NOTE: the `configuration-properties.classe` should whitelist the `my.dugong` property defined in the `MyLogConsumerProperties` class, while the `configuration-properties.names` whitelists the `other.orca` property in the `MyOtherProperties` class.

I've built the app and register the jar it in SCDF. The info shows: 
<img width="689" alt="Screen Shot 2020-01-22 at 4 45 48 PM" src="https://user-images.githubusercontent.com/1351573/72909372-316dda80-3d37-11ea-8989-547d6e58d816.png">

Above demonstrates that one can withe list properties without a dedicated metadata artifact! 

## IMPORTANT:
*  The whitelisting works only with JAR app artifacts! It will not work for App Docker Images. For later a dedicated metadata artifact is required. 
*  The `configuration-properties.names` can white-list only properties defined in `@ConfigurationProperties` property class, registered with the app. The `@Value` defined properties will NOT work!
