### ISSUE TITLE
Add a recipe for installing SCDF for batch-only mode

### ISSUE THREAD

**Issue by sabbyanandan** [spring-io/dataflow.spring.io#202]
As a user, I'd like to migrate over from SBA to SCDF, but I don't have a recipe as to how to manually provision SCDF for batch-mode only.

**Acceptance:**
- At the beginning of the [recipe](https://dataflow.spring.io/docs/recipes/), the prerequisites are defined
- On the recipe, I'm guided with the installation steps and the feature toggles to configure for batch-only mode
- The recipe includes a sample output of the various components running locally in the laptop
- All throughout the recipe, I'm guided with deep-dive docs and ref. guide links for further reading
- The recipe is also cross-linked from the manual [Local installation guide](https://dataflow.spring.io/docs/installation/local/manual/) (perhaps as a new right-nav section with the link redirecting to the recipe)

**Comment by Buzzardo** [comment]
I would like to add it as fourth option called "Batch-only Mode" under "Local Machine". My concern with putting it as right-menu option within the Local topic is that people will see all those other steps first and inadvertently do them, only to then need to go back and do something else to get into batch-only mode.

What do you think?

**Comment by sabbyanandan** [comment]
We support three platforms, and the local is one of them. 

I'd still vote for continuing with the existing setup and keep the batch-only instructions as a recipe (outside of installation section altogether) — all we need is a link to share when it comes up anyway. Also, it is only applicable to the "manual" installation approach, so if we could tie it under that somehow, it would be better.
