### ISSUE TITLE
Update K8s getting-started instructions to point from Helm2 -> Helm3

### ISSUE THREAD

**Issue by sabbyanandan** [spring-io/dataflow.spring.io#220]
Helm 2.x is slated for EOL in Nov 2020. Once when the chart is compatible with Helm 3.0, we will have to switch the instructions to point to Helm 3.0, and explicitly also call our Helm 2.0's EOL timeline in a NOTE.

**Comment by chrisjs** [comment]
for this issue:

* update helm page of microsite with a NOTE indicating helm2 is EOL Nov and our existing chart will be converted to Helm 3 at that time.

* additionally, add links pointing users to migration guides so they can plan and review based on their requirements and environment. we would not be providing guidance on doing so:
** https://helm.sh/docs/topics/v2_v3_migration/
** https://docs.bitnami.com/tutorials/resolve-helm2-helm3-post-migration-issues/
