### ISSUE TITLE
Latest releases aren't included in the announcements

### ISSUE THREAD

**Issue by sabbyanandan** [spring-io/dataflow.spring.io#248]
If this is going to be all manual, it is highly likely we will continue to miss updating it, and it defeats the purpose of having this section in the Microsite. 

Let's just look into ways to automate adding the blog pointers for known project releases.

**Comment by ilayaperumalg** [comment]
The variables used in the settings are the JSON file (versions.json and the variables.json) and given the way we use these to reflect in the generated microsite, there is no obvious way to automate this process without having to manually update the actual version to update (no maven POM here).

One of the possible approaches we can do is to document the process in the release doc. I have updated the same in the document. Hence, closing it as done. Feel free to re-open if you have any other suggestions in terms of automating this.

**Comment by sabbyanandan** [comment]
I still don't see any of the 2.5.x blogs, nor are they current for SCSt/SCT. If they are not going to be maintained either manually or in an automated manner, the purpose of having them in the first place is lost.

**Comment by sabbyanandan** [comment]
In case this is not clear, I am referring to these tiles:
![image](https://user-images.githubusercontent.com/1562654/86202922-6b2de300-bb18-11ea-96d3-6b0979a7d2f7.png)

**Comment by ilayaperumalg** [comment]
I see what you mean now. Sorry, it was my mistake as I referred to updating the latest releases in the documentation versions. Overlooked the part you mentioned as announcements and blogs from the original description.

**Comment by ilayaperumalg** [comment]
This is addressed via https://github.com/spring-io/dataflow.spring.io/commit/ee77741a80a74d32330d2634db52d6c991ceee1a and also updated the release do c on updating the news section post release announcement.
