### ISSUE TITLE
Move from bamboo to gh actions

### ISSUE THREAD

**Issue by jvalkeal** [spring-io/dataflow.spring.io#268]
Move away from bamboo to do all using gh actions

- [x] setup secrets
- [x] ci build and deploy
- [x] ci link checks
- [x] prod deploy using workflow dispatch

**Comment by sabbyanandan** [comment]
@jvalkeal: Any reason why we cannot promote to production yet?

**Comment by jvalkeal** [comment]
right, this was done few weeks ago!
