### ISSUE TITLE
Add consistent link to the Github repository for site

### ISSUE THREAD

**Issue by mminella** [spring-io/dataflow.spring.io#281]
Since the code for the site is located in this repository and open to community support, we should have a link to here in the footer/etc so that it is easy to find.

**Comment by sabbyanandan** [comment]
@mminella: Each page includes a button (see example below) towards the end to edit/submit PRs to fix issues on the given page. Would that satisfy what you're asking? Perhaps I am misinterpreting your description.

![image](https://user-images.githubusercontent.com/1562654/93385421-1ba7ab00-f81b-11ea-8573-f59b7f15d42c.png)

**Comment by mminella** [comment]
Nope...you have it right. I'm not sure how I missed that. Crawling back under my rock ;)
