### ISSUE TITLE
Missing reference in Batch-only Mode page

### ISSUE THREAD

**Issue by benas** [spring-io/dataflow.spring.io#284]
It seems like there is a missing reference in the last sentence of the first paragraph here https://dataflow.spring.io/docs/recipes/batch/batch-only-mode/#prerequisites :

```
Batch-only mode requires only Spring Cloud Data Flow Server.
You do not need Spring Cloud Data Flow Shell or Spring Cloud Skipper, though you can still use it. See XXX
```

**Comment by sabbyanandan** [comment]
Fixed this in 2.6.x and master. Thanks, @benas.
