### ISSUE TITLE
Need to update ctrcommand line arg and property documentation

### ISSUE THREAD

**Issue by cppwfs** [spring-io/dataflow.spring.io#337]
For issues https://github.com/spring-cloud/spring-cloud-dataflow/issues/4265 and https://github.com/spring-cloud/spring-cloud-dataflow/issues/4258 we need update the documentation for how users pass properties to the tasks in  composed task graph.
For example a composed task that looks like `AAA: timestamp && BBB: timestamp` :
Command Line args now look like: 
```
--composed-task-app-arguments.app.AAA.0=--timestamp.format=YYYY  --composed-task-app-arguments.app.BBB.0=--timestamp.format=DD=YYYY
```

Properties now look like:
```
app.AAA.timestamp.format=YYYY
app.BBB.timestamp.format=DD
```

**Comment by ilayaperumalg** [comment]
This is addressed via https://github.com/spring-io/dataflow.spring.io/pull/397. Closing as resolved.
