### ISSUE TITLE
Different file name format - 3.kubectl.md 

### ISSUE THREAD

**Issue by LOG-INFO** [spring-io/dataflow.spring.io#340]
In [`1-installation /3-kubernetes` of branch `2.7.x`](https://github.com/spring-io/dataflow.spring.io/tree/2.7.x/content/documentation/pages/1-installation/3-kubernetes), `kubectl` markdown file name format is different from others.

Other file's name format is `{sequence}-{subject}.md`(e.g. `2-helm.md`), but `kubectl` file name is `3.kubectl.md`.

**I hope to change `3.kubectl.md` to `3-kubectl.md`**

**Comment by sabbyanandan** [comment]
Changes merged.
