### ISSUE TITLE
Add Entry on Shell entrypoint affect on Job Params.

### ISSUE THREAD

**Issue by cppwfs** [spring-io/dataflow.spring.io#352]
Add detail to the shell entrypoint docs that statest that JobParams can not be passed to a batchjob using this entrypoint.

**Comment by benas** [comment]
I would also add a note that this entrypoint style prevents graceful shutdown of apps which is very important for restarts. Here is an excerpt from [Docker docs](https://docs.docker.com/engine/reference/builder/#entrypoint), which recommend using the `exec` form:

```
The exec form, which is the preferred form:

[...]

The shell form prevents any CMD or run command line arguments from being used, but has the disadvantage
that your ENTRYPOINT will be started as a subcommand of /bin/sh -c, which does not pass signals.
This means that the executable will not be the container's PID 1 - and will not receive Unix signals -
so your executable will not receive a SIGTERM from docker stop <container>.
```
