### ISSUE TITLE
Commercial features tile redirecting to outdated docs

### ISSUE THREAD

**Issue by sabbyanandan** [spring-io/dataflow.spring.io#366]
![image](https://user-images.githubusercontent.com/1562654/119903260-52cb7180-befd-11eb-804e-2716d4324034.png)

Clicking the tile is redirecting to 1.1 K8s docs, and it should instead point to the latest' PRO features.

Also, we need to rethink how this can go to both CF and K8s docs since we will now have the PRO server mounted at both the commercial variants.

**Comment by ilayaperumalg** [comment]
We need to come up with two tiles view here which re-directs to K8s and CF tile commercial experience.

**Comment by ilayaperumalg** [comment]
@oodamien Could you add a new tile view which redirects CF tile to this page: https://docs.pivotal.io/scdf/1-10/

and have the K8s pointing to https://docs.pivotal.io/scdf-k8s/1-2/index.html

**Comment by oodamien** [comment]
Preview:

![image](https://user-images.githubusercontent.com/487067/120493983-b6e9ac00-c3bb-11eb-89e8-0b6297331cc3.png)

I will need help for the title/description for this 2 tiles

**Comment by sabbyanandan** [comment]
@oodamien: I'd add 1 tile with the title "Commercial Features guides" , and that can redirect to a different page with two links: 1- "Feature guides for Tanzu Application Service" / 2- "Feature guides for Kubernetes".

**Comment by sabbyanandan** [comment]
![image](https://user-images.githubusercontent.com/1562654/120682808-bd2a6780-c451-11eb-91be-a10cb3d040b8.png)

This appears to look like what I had in my head as a suggestion, so I am good.
