### ISSUE TITLE
docker-compose-dood.yml fails to install Docker CLI

### ISSUE THREAD

**Issue by adar2** [spring-io/dataflow.spring.io#502]
The docker-compose-dood.yml configuration is not installing the Docker CLI as expected. This deviation from the expected behavior is hindering the intended functionality of the Docker Compose setup.

**Comment by onobc** [comment]
Hi @adar2 - thanks for the report. We have moved the ticket to the Dataflow repo https://github.com/spring-cloud/spring-cloud-dataflow/issues/5582.
